config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :pages
  # Defines the root path route ("/")
  # root "articles#index"

  get 'bookings/download_information', to: 'bookings#download_information', as: 'download_information'

  resources :chairs do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :chair

  validates :date_start, :date_end, presence: true
  validate :date_end_after_date_start

  def date_end_after_date_start
    if date_end < date_start
      errors.add(:date_end, "can't be before date start")
    end
  end
end

app/models/chair.rb
class Chair < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  validates :name, :address, :description, :price, :photos, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Referneces
  has_many :chairs, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # cloudinary photos
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_after_action :verify_authorized, only: [:download_information]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_chair, only: [:new, :create]

  # al ser la ruta nesteada con chair, usamos el chair_id para encontrar la silla

  def index
    @bookings = policy_scope(Booking)
  end

  def show
    authorize @booking
    @chair = @booking.chair
  end

  def new
    @booking = Booking.new
    authorize @chair
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.chair = @chair
    @booking.user = current_user
    authorize @chair
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to bookings_path, notice: 'Booking was successfully deleted.'
  end

  def download_information
    @booking = Booking.find(params[:booking][:id])
    respond_to do |format|
      format.html
      format.pdf { render pdf: "Id afiliado: ", template: 'bookings/pdf' }
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date_start, :date_end)
  end

  def set_chair
    @chair = Chair.find(params[:chair_id])
  end
end

app/controllers/chairs_controller.rb
class ChairsController < ApplicationController
  before_action :set_chair, only: %i[show edit update destroy]
  def index
    @chairs = policy_scope(Chair)
  end

  def show
    authorize @chair
  end

  def new
    @chair = Chair.new
    authorize @chair
  end

  def create
    @chair = Chair.new(chair_params)
    @chair.user = current_user
    authorize @chair
    if @chair.save
      redirect_to chair_path(@chair)
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    authorize @chair
  end

  def update
    authorize @chair
    @chair.update(chair_params)
  end

  def destroy
    authorize @chair
    @chair.destroy
    redirect_to chairs_path, status: :see_other
  end

  private

  def set_chair
    @chair = Chair.find(params[:id])
  end

  def chair_params
    params.require(:chair).permit(:name, :address, :description, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    # Fetch all chairs and assign them to the @chairs instance variable
    @chairs = Chair.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<%= stylesheet_link_tag 'bookings' %>
<div class="bookings-container mt-5">
    <h1 class="bookings-title">Here are your upcoming bookings</h1>

    <div class="bookings-cards">
        <% current_user.bookings.each do |booking| %>
            <div class="booking-card">
                <h2 class="booking-chair-name"><%= link_to booking.chair.name, booking_path(booking) %></h2>
                <div class="booking-dates">
                    <% if booking.date_start.present? %>
                        <p><strong>Start Date:</strong> <%= booking.date_start.strftime("%B %-d, %Y") %></p>
                    <% else %>
                        <p><strong>Start Date:</strong> Not specified</p>
                    <% end %>

                    <% if booking.date_end.present? %>
                        <p><strong>End Date:</strong> <%= booking.date_end.strftime("%B %-d, %Y") %></p>
                    <% else %>
                        <p><strong>End Date:</strong> Not specified</p>
                    <% end %>
                </div>
                <p class="booking-address"><strong>Location:</strong> <%= booking.chair.address %></p>
                <%= link_to 'Delete', booking_path(booking), data:{turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this booking?' }, class: 'delete-booking-button' %>
            </div>
        <% end %>
    </div>

    <%= link_to "Go Back", root_path, class:"btn btn-success"%>

app/views/bookings/new.html.erb
<div class="bg-color py-5 mt-5">

    <div class="container w-50 shadow bg-white p-3">
        <%= simple_form_for [@chair, @booking], url: chair_bookings_path(@chair) do |f| %>
            <%= f.input :date_start, label:"Start date", class:"form-control", html5: true, input_html: { min: Date.today } %>
            <%= f.input :date_end, label:"End date", class:"form-control", html5: true, input_html: { min: Date.today } %>
            <%#= f.input :image_url, class:"form-control" %>
            <%= f.submit "Reserve this chair!", class:"btn btn-success mb-4 sm" %>
        <% end %>
    </div>
</div>

app/views/bookings/pdf.pdf.erb
<div class="bg-color py-5">
  <div class="container w-50 shadow bg-white p-3">
    <div class="d-flex">
      <div class="photo-show m-auto">
        <h1>Your Chair is Confirmed!</h1>
        <p>Your booking starts on: <%= @booking.date_start %></p>
        <p>And it ends on: <%= @booking.date_end %></p>
        <h4>Information on your chair:</h4>
        <% @booking.chair.photos.each do |photo| %>
          <p><%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill%></p>
        <% end %>
        <p><%= @booking.chair.name %></p>
        <p>$<%= @booking.chair.price %></p>
        <p><%= @booking.chair.description %></p>
        <p>Your chair is located at <%= @booking.chair.address %></p>
        <%= link_to 'Download information', download_information_path(format: :pdf), target:"_blank", class: 'btn btn-success' %>
      </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="bg-color py-5 mt-5">
  <div class="container w-50 shadow bg-white p-5 mb-10 rounded-5">
    <h1 class="text-center">Your Chair is Confirmed!</h1>


    <div class="d-flex justify-content-center">
      <div class="photo-show mx-0 px-0 w-100">
        <% @booking.chair.photos.each do |photo| %>
         <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill, class: "w-100"%>
        <% end %>
      </div>
    </div>

    <div class="d-flex mt-5 mb-5">

      <div class="col-6 p-2">
        <h4>Information on your chair:</h4>
        <p><%= @booking.chair.name %></p>
        <p>$<%= @booking.chair.price %></p>
        <p><%= @booking.chair.description %></p>
        <p>Your chair is located at <%= @booking.chair.address %></p>
      </div>

      <div class="col-6 mx-0 my-2 price-rating-rentbutton-div">
        <p>Your booking starts on: </p>
        <p><b><%= @booking.date_start %></b></p>
        <p>And it ends on: </p>
        <p><b><%= @booking.date_end %></b></p>
      </div>

    </div>

    <div class="text-center">
      <%= link_to 'Download information', download_information_path(params: {booking: @booking}, format: :pdf), target:"_blank", class: 'btn btn-success' %>
    </div>
  </div>
</div>

<button id="back-button" onclick="window.history.back();" style="position: fixed; bottom: 20px; left: 20px; background-color: #4CAF50; border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 50px;">Go Back</button>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/chairs/edit.html.erb
<div class="bg-color py-5 mt-5">
  <div class="container mt-5">
      <div class="row">
          <div class="col-md-8 offset-md-2">
              <h2>Edit Chair Listing</h2>

              <%= simple_form_for @chair do |f| %>
                  <%= f.input :name, label: "Chair Name", class: "form-control", input_html: { maxlength: 50 } %>
                  <%= f.input :description, as: :text, label: "Description", class: "form-control", input_html: { maxlength: 300 } %>
                  <%= f.input :address, label: "Address", class: "form-control" %>
                  <%= f.input :price, label: "Price per Day ($)", class: "form-control" %>
                  <%= f.input :photos, as: :file, label: "Photos", input_html: { multiple: true } %>
                  <%= f.submit "Update Chair", class: "btn btn-primary mt-3" %>
              <% end %>

              <div class="mt-3">
                  <%= link_to "Cancel", @chair, class: "btn btn-secondary" %>
              </div>
          </div>
      </div>
  </div>
  <button onclick="window.history.back();" style="position: fixed; bottom: 20px; left: 20px; z-index: 99;" class="btn btn-secondary">Go Back</button>
</div>

app/views/chairs/index.html.erb
<div class="banner">
<%= stylesheet_link_tag 'chairs' %>
  <div class="container">
    <h1 style="text-align: center; margin-top: 30px; font-size: 36px; color: #333;">Your Published Chairs</h1>
  </div>
</div>

<div class="container">
  <div class="cards-container">
    <% current_user.chairs.each do |chair| %>
      <%= link_to chair_path(chair), class: "card-chair" do %>
        <div class="card-chair-image-container">
          <% chair.photos.each do |photo| %>
            <%= cl_image_tag photo.key, crop: :fill %>
          <% end %>
          <% if user_signed_in? && current_user.photo.attached? %>
            <%= image_tag current_user.photo, class: "avatar card-chair-user avatar-bordered" %>
          <% end %>
        </div>
        <div class="card-chair-infos">
          <h2 class="card-title"><%= chair.name %></h2>
          <h3 class="card-chair-pricing">$<%= chair.price %></h3>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="go-back-button-container" style="text-align: center; margin-top: 30px;">
  <button onclick="window.history.back();" class="go-back-button">Go Back</button>
</div>

app/views/chairs/new.html.erb
<div class="bg-color py-5 mt-5">
  <div class="container w-50 shadow bg-white p-3">
    <!-- Formulario -->
    <%= simple_form_for @chair do |f| %>
      <%= f.input :name, label:"Chair name", class:"form-control", input_html: { maxlength: 20 } %>
      <%= f.input :description, as: :text, label:"Details", input_html: { maxlength: 300 } %>
      <%= f.input :address, label:"Address", class:"form-control" %>
      <%= f.input :price, label:"Price per Day", class:"form-control" %>
      <%= f.input :photos, as: :file, label:"Photos", input_html: { multiple: true } %>
      <%= f.submit "Post your chair!", class:"btn btn-success mb-4 sm" %>
    <% end %>
  </div>
</div>

app/views/chairs/show.html.erb
<div class="bg-color py-5 mt-5">
  <div class="bannertwo">
    <div class="container w-50 shadow bg-white p-5 mb-5 rounded-5">
     
      <div class="mt-3 mb-3">
        <h1><%= @chair.name %></h1>
      </div>
      <div class="d-flex justify-content-center">
        <div class="photo-show mx-0 w-100">
          <% @chair.photos.each do |photo|%>
            <p><%= cl_image_tag photo.key, height: 300, crop: :fill, class: "w-100", style: "object-fit: cover" %></p>
          <% end %>
        </div>
      </div>
      <div class="d-flex py-3 px-0 justify-content-between">
        <div>
          <p><%= @chair.description %></p>
          <hr>
          <p><strong>This chair is located at:</strong></p>
          <p><%= @chair.address %></p>
          <p><strong>This chair belongs to: </strong></p>
          <p><%= @chair.user.email %></p>
        </div>


        <div class="price-rating-rentbutton-div mx-0 my-0 d-flex align-items-center">
          <div>
            <div class=" d-flex justify-content-between">
              <div class="price-chair-show">
                <%= number_to_currency(@chair.price, unit: "$", separator: ".")  %>
              </div>
              <p><%= image_tag "rating-star.jpg", height: 12, width: 12 %> <%= @chair.rating %></p>
            </div>
            <div class="button-chair-show">
                <% if current_user != @chair.user %>
                  <%= link_to "Rent this chair!", new_chair_booking_path(@chair), class:"btn btn-success" %>
                <% end %>
            </div>
          </div>
        </div>
      </div>

      <% if current_user == @chair.user %>
        <hr>
        <div class="d-flex mx-0 px-0 justify-content-around">
          <%= link_to "Edit Chair", edit_chair_path(@chair), class:"btn btn-success p-2" %>
          <%= button_to "Delete Chair", @chair, method: :delete, class:"btn btn-danger text-white p-2" %>
        </div>
      <% end %>


    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirCNC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <%# Fonts  Below %>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;800&family=Press+Start+2P&family=Red+Hat+Mono&family=Roboto:wght@100;500&family=VT323&display=swap" rel="stylesheet">
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>

  <body>
    <div class="contenedor">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>

  </body>
  <%= render "shared/footer" %>
</html>

app/views/pages/home.html.erb
<div class="bg-color p-4 mt-4">
  <div class="container my-5 shadow p-3 w-75 card-color text-center">
    <h1>Welcome to AirCnC</h1>
    <p>Rent chairs for any occasion!</p>

    <!-- <div class="search-bar p-3">
      <%= simple_form_for :search, url: chairs_path, method: :get, html: { class: 'form-inline' } do |f| %>
        <%= f.input :query, label: false, input_html: { placeholder: 'Search for chairs...', class: 'form-control' } %>
        <%= f.button :submit, 'Search', class: 'btn btn-success ml-2' %>
      <% end %>
    </div> -->

    <% if user_signed_in? %>
      <p>Welcome, <%= current_user.email %>!</p>
      <!-- <%= link_to 'My Bookings', bookings_path, class: 'btn btn-success' %>
      <%= link_to 'List a Chair', new_chair_path, class: 'btn btn-secondary' %> -->
    <% end %>
  </div>

  <div class="container my-5 shadow p-3 w-75 card-color text-center mt-4">
      <div class="row">
        <div class="col-12">
          <h4>Chairs</h4>
        </div>
      </div>
      <!-- ui kit template -->
      <div class="cards-container">
        <% @chairs.each do |chair| %>
          <%= link_to chair_path(chair) do %>
            <div class="card-chair">
              <% chair.photos.each do |photo|%>
                <%= cl_image_tag photo.key, crop: :fill %>
              <% end %>
              <div class="card-chair-infos">
                <div>
                  <h2 class="card-title"><%= chair.name %></h2>
                </div>
                <h2 class="card-chair-pricing mt-3">$<%= chair.price %></h2>
                <% if user_signed_in? %>
                  <% if chair.user.photo.attached? %>
                    <%= image_tag chair.user.photo, class: "avatar card-chair-user avatar-bordered" %>
                  <% else %>
                    <%= image_tag "avatar_chair.jpg", class: "avatar card-chair-user avatar-bordered" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="text-center mt-3">
        <button id="show-more" class="btn btn-success round">Show more</button>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-links">
    <a href="https://github.com/MKant0/AirCNC"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p><%="With AirCnC, you find your perfect chair!" %></p>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag ("AirCnCLogo3") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item-font active mt-1">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="btn btn-outline-success btn-sm nav-item mx-1">
            <%= link_to "New Post", new_chair_path, class: "nav-link"%>
          </li>
          <b><li class="nav-item active mt-1 mx-1" id="rch">
            <%= link_to "Rent a chair", root_path, class: "nav-link" %>
          </li></b>
          <li class="nav-item-dropdown dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
              <%= image_tag current_user.photo, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <%= image_tag "avatar_chair.jpg", class: "avatar", alt: "dropdown menu" %>
              <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Publications", chairs_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item-font mt-1">
            <%= link_to "Post a chair", user_session_path, class: "nav-link" %>
          </li>
          <li class="btn btn-outline-success btn-sm nav-item mx-1">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
          </li>
          <b><li class="nav-item active mt-1 mx-1" id="rch">
            <%= link_to "Login", user_session_path, class: "nav-link" %>
            </li>
          </b>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<%# Codigo De Vanilla JS para fixed navbar %>
<%# <script>
  document.addEventListener("scroll", function () {
  const navbar = document.querySelector(".navbar-lewagon");
  const navbarHeight = 100;
  const distanceFromTop = Math.abs(
    document.body.getBoundingClientRect().top
  );
  if (window.scrollY > 0) navbar.classList.add("fixed-top");
  else navbar.classList.remove("fixed-top");
  console.log(window.scrollY)
  console.log(window.innerHeight)
});
</script> %>